// Generated by CoffeeScript 1.10.0
(function() {
  var config, fs, pjson, sslOptions;

  pjson = require('./package.json');

  fs = require('fs');

  if ((process.env.NODE_ENV == null) || process.env.NODE_ENV === 'local') {
    config = {
      env: 'local',
      httpsPort: process.env.HTTPSPORT || '8443',
      httpPort: process.env.HTTPPORT || '8080',
      cdn: '/build/bundle.js'
    };
    sslOptions = {
      key: process.env.KEY || fs.readFileSync('/etc/letsencrypt/live/liive.io/privkey.pem'),
      cert: process.env.CERT || fs.readFileSync('/etc/letsencrypt/live/liive.io/fullchain.pem'),
      ca: process.env.CA || fs.readFileSync('/etc/letsencrypt/live/liive.io/chain.pem'),
      requestCert: false,
      rejectUnauthorized: false
    };
  } else if (process.env.HEROKU != null) {
    config = {
      env: process.env.NODE_ENV || 'develop',
      httpPort: process.env.PORT || '',
      cdn: '/build/bundle.js',
      heroku: true
    };
    sslOptions = null;
    if ((process.env.KEY != null) && (process.env.CERT != null) && (process.env.CA != null)) {
      sslOptions = {
        key: process.env.KEY,
        cert: process.env.CERT,
        ca: process.env.CA,
        requestCert: false,
        rejectUnauthorized: false
      };
      config.httpsPort = process.env.PORT || '';
    }
  } else {
    config = {
      env: process.env.NODE_ENV || 'develop',
      httpPort: process.env.OPENSHIFT_NODEJS_PORT || '',
      httpIp: process.env.OPENSHIFT_NODEJS_IP,
      cdn: '/build/bundle.js'
    };
    sslOptions = null;
    if ((process.env.KEY != null) && (process.env.CERT != null) && (process.env.CA != null)) {
      sslOptions = {
        key: process.env.KEY,
        cert: process.env.CERT,
        ca: process.env.CA,
        requestCert: false,
        rejectUnauthorized: false
      };
      config.httpsPort = process.env.PORT || '';
    }
  }

  config.title = pjson.title;

  config.version = pjson.version;

  module.exports = [config, sslOptions];

}).call(this);

//# sourceMappingURL=config.js.map
