// Generated by CoffeeScript 1.10.0
(function() {
  var Handshake, io;

  io = require('socket.io');

  Handshake = (function() {
    var _connect, _exchange, _leave, reactions, rtcChannel, socket;

    socket = io();

    reactions = null;

    rtcChannel = null;

    function Handshake(_rtcChannel, _reactions) {
      reactions = _reactions;
      rtcChannel = _rtcChannel;
      socket.on('connect', _connect);
      socket.on('exchange', _exchange);
      socket.on('leave', _leave);
    }

    Handshake.prototype.join = function(id, callback) {
      return socket.emit('join', id, (function(_this) {
        return function(socketIds) {
          console.log('join', socketIds);
          return callback(null, socketIds);
        };
      })(this));
    };

    Handshake.prototype.leave = function(id, callback) {};

    Handshake.prototype.candidate = function(id, _candidate) {
      return socket.emit('exchange', {
        'to': id,
        'candidate': candidate
      });
    };

    Handshake.prototype.description = function(id, _description) {
      return socket.emit('exchange', {
        'to': id,
        'sdp': description
      });
    };

    _connect = function(data) {
      if (reactions.didConnect != null) {
        return reactions.didConnect(data);
      }
    };

    _exchange = function(data) {
      if (reactions.didExchange != null) {
        return reactions.didExchange(data);
      }
    };

    _leave = function(id) {
      if (reactions.didLeave != null) {
        return reactions.didLeave(id);
      }
    };

    return Handshake;

  })();

  module.exports = Handshake;

}).call(this);

//# sourceMappingURL=Handshake.js.map
