// Generated by CoffeeScript 1.10.0
(function() {
  var Handshake, RTCChannel, Room;

  RTCChannel = require('./RTCChannel');

  Handshake = require('./Handshake');

  Room = (function() {
    var channel, didConnect, didExchange, didLeave, exchangeCandidate, exchangeDescription, handshake;

    handshake = null;

    channel = null;

    function Room(configuration, _observers) {
      channel = new RTCChannel(configuration, _observers, {
        exchangeDescription: exchangeDescription,
        exchangeCandidate: exchangeCandidate
      });
      handshake = new HandShake(configuration, {
        didConnect: didConnect,
        didExchange: didExchange,
        didLeave: didLeave
      });
    }

    Room.prototype.join = function(roomId, callback) {
      return handshake.join('join', roomID, function(error, ids) {
        var i, id, len;
        console.log('join', ids);
        for (i = 0, len = ids.length; i < len; i++) {
          id = ids[i];
          channel.createListener(id, true);
        }
        if (callback != null) {
          return callback(null, ids);
        }
      });
    };

    Room.prototype.leave = function(roomId, callback) {
      return handshake.leave(roomId, callback);
    };

    Room.prototype.say = function(text) {
      return channel.send(text);
    };

    exchangeDescription = function(id, description) {
      if (id !== null) {
        return handshake.description(id, description);
      }
    };

    exchangeCandidate = function(id, candidate) {
      if (id !== null) {
        return handshake.candidate(id, candidate);
      }
    };

    didConnect = function(data) {
      console.log("connect: data is -->" + data);
      return channel.getMedia({
        "audio": true,
        "video": true
      }, function(stream) {
        return console.log("did Connect: " + stream);
      });
    };

    didExchange = function(data) {
      return channel.exchange(data, function(error, result) {
        if (error != null) {
          console.log(error);
        }
        if ((result != null) && (reactions.didExchange != null)) {
          console.log("did Exchange: " + result.id + " desc: " + result.description);
          return handshake.candidate(result.id, result.description);
        }
      });
    };

    didLeave = function(id) {
      return channel.deleteListener(id, function(error, id) {
        return console.log("did Leave: " + id);
      });
    };

    return Room;

  })();

}).call(this);

//# sourceMappingURL=Room.js.map
