// Generated by CoffeeScript 1.10.0
(function() {
  var Handshake, io;

  io = require('socket.io');

  Handshake = (function() {
    var connect, exchange, leave, reactions, socket;

    socket = io();

    reactions = null;

    function Handshake(_reactions) {
      reactions = _reactions;
      socket.on('connect', connect);
      socket.on('exchange', exchange);
      socket.on('leave', leave);
    }

    Handshake.prototype.join = function(id, callback) {
      return socket.emit('join', id, (function(_this) {
        return function(socketIds) {
          console.log('join', socketIds);
          return callback(socketIds);
        };
      })(this));
    };

    Handshake.prototype.candidate = function(id, candidate) {
      return socket.emit('exchange', {
        'to': id,
        'candidate': candidate
      });
    };

    Handshake.prototype.description = function(id, description) {
      return socket.emit('exchange', {
        'to': id,
        'sdp': description
      });
    };

    connect = function(data) {
      if (reactions.didConnect != null) {
        return reactions.didConnect(data);
      }
    };

    exchange = function(data) {
      if (reactions.didExchange != null) {
        return reactions.didExchange(data);
      }
    };

    leave = function(id) {
      if (reactions.didLeave != null) {
        return reactions.didLeave(id);
      }
    };

    return Handshake;

  })();

  module.exports = Handshake;

}).call(this);

//# sourceMappingURL=Handshake.js.map
