// Generated by CoffeeScript 1.10.0
(function() {
  var Room;

  Room = (function() {
    var INSIDE, OUTSIDE, handshake, room, state;

    OUTSIDE = 'outside';

    INSIDE = 'inside';

    room = null;

    state = OUTSIDE;

    handshake = null;

    function Room(configuration) {
      state = OUTSIDE;
      handshake = new HandShake(configuration, {
        exchange: function(data) {
          return console.log('exchange');
        },
        leave: function(socketId) {
          return console.log('leave');
        },
        connect: function(data) {
          return console.log('connect');
        }
      });
    }

    Room.prototype.join = function(roomId, callback) {
      return handshake.requestJoin('join', roomID, callback);
    };

    Room.prototype.leave = function(roomId, callback) {};

    Room.prototype.say = function(text) {};

    return Room;

  })();

}).call(this);

//# sourceMappingURL=Room.js.map
