// Generated by CoffeeScript 1.10.0
(function() {
  var Handshake, RTCChannel, Room;

  RTCChannel = require('../lib/RTCChannel');

  Handshake = require('../lib/Handshake');

  Room = (function() {
    var channel, handshake;

    handshake = null;

    channel = null;

    function Room(configuration, _observers, _reactions, _listeners) {
      channel = new RTCChannel(configuration, _listeners);
      handshake = new HandShake(configuration, _observers, _reactions);
    }

    Room.prototype.join = function(roomId, callback) {
      return handshake.requestJoin('join', roomID, function(ids) {
        var i, id, len, results;
        console.log('join', ids);
        results = [];
        for (i = 0, len = ids.length; i < len; i++) {
          id = ids[i];
          results.push(rtcChannel.createListener(id, true));
        }
        return results;
      });
    };

    Room.prototype.leave = function(roomId, callback) {};

    Room.prototype.say = function(text) {};

    return Room;

  })();

}).call(this);

//# sourceMappingURL=Room.js.map
